st='hellO wOrLd'
print(st.lower())
print(st.upper())
print(st.casefold())
print(st.capitalize())
print(st.title())
print(st.center(20,'#'))
print(st.ljust(20,'*'))                            #string methods
print(st.isalpha())
print(st.count('O'))
print(st.index('O'))
print(st.rindex('O'))
print(st.find('G'))
print(st.rfind('O'))
print(st.split(' '))
print(list(st))
ls=list(st)
ls.remove(' ')
print(ls)
s=str(ls)
print(s+'Hii')